// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njwucrytjuyfxotypkwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qd3Vjcnl0anV5ZnhvdHlwa3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTY3NzYsImV4cCI6MjA3MTA3Mjc3Nn0.VolRosOCac7Zd205wl-5xZGFLMOe9XsO11lGPR6wEz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});